# theme.toml template for a Hugo theme

name = "afs"
license = "Apache License 2.0"
licenselink = "https://www.apache.org/licenses/LICENSE-2.0"
description = "afs"
homepage = "https://afs.github.io/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Andy Seaborne"
  homepage = "https://afs.github.io/"
